package miniJava.SyntacticAnalyzer;

public enum TokenKind {ID, NUM, GREATER, LESS, EQUAL, LESSEQUAL, GREATEREQUAL, NOTEQUAL, 
	AND, OR, NOT, PLUS, MINUS, TIMES, DIVIDE, EOT, CLASS, VOID, PUBLIC, PRIVATE, STATIC, INT, BOOLEAN, LPAREN, RPAREN, LBRACE, RBRACE,
	COMMA, SEMICOL, THIS, DOT, ASSIGN, RETURN, IF, ELSE, WHILE, TRUE, FALSE, NEW, LBRACKET, RBRACKET, ERROR, NULL
	}
